PLATFORM=i686-pc-mingw32-
#put your mingw32 prefix
COMPILER=g++

all:
	$(PLATFORM)$(COMPILER) tchar_ex.cpp -o tchar_ex.exe -mwindows
	$(PLATFORM)$(COMPILER) tchar_ex2.cpp -o hello.exe
clean:
	rm -rf *.exe
